Repository yyyar/gobetween, pull requests merged in 2020-01, with the labels that each got.

#259 typo in README.md
  README.md
Labels: improvement

#222 SRV backend IPv6 support
  src/discovery/srv.go
Labels: feature, improvement

#232 add json format support for logs
  config/gobetween.toml
  main.go
  src/config/config.go
  src/logging/log.go
Labels: feature

#252 Do healthcheck upon worker startup without delay
  src/healthcheck/worker.go
Labels: improvement

#261 fix startup race condition
  main.go
  src/api/api.go
Labels: improvement
